name: Docker Image test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Push Container Image
    runs-on: self-hosted

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Amazon ECR Authentication
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: SCM Checkout
        uses: actions/checkout@v2

      - name: Build, tag, and push Backend api image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo Image Tag - $IMAGE_TAG
          docker build --build-arg API_VERSION_HASH=${{ github.sha }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f .docker/dev/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
